<!-- Footer Start-->
<footer>
    <div class="footer ">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-sm-6">
                    <div class="footer-wedget1">
                        <h2>Sobre</h2>
                        <p>Lorem ipsum dolor sit amet, te est illum aliquam complectitur, quo te soluta utroque lucilius, eos tritani tacimates id. No usu nostrud quaeque lobortis. Utinam primis id nam.</p>
                        <ul>
                            <li><a href=""><i class="fa fa-facebook"></i></a></li>
                            <li><a href=""><i class="fa fa-twitter"></i></a></li>
                            <li><a href=""><i class="fa fa-google"></i></a></li>
                            <li><a href=""><i class="fa fa-skype"></i></a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6">
                    <div class="footer-wedget2">
                        <h2>Menu</h2>
                        <ul>
                            <li><a href="#"></i>Home</a></li>
                            <li><a href="#"></i>Videos</a></li>
                            <li><a href="#"></i>Aulas Resumidas</a></li>
                            <li><a href="#"></i>Textos e Artigos</a></li>
                            <li><a href="#"></i>Informes</a></li>
                            <li><a href="#"></i>Sitios</a></li>
                            <li><a href="#"></i>Professor</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6">
                    <div class="contact-info">
                        <h2>Contato</h2>
                        <div class="contactsingle-info">
                            <h2>Email: </h2>
                            <p>info@yourwebsite.com</p>
                        </div>
                        <div class="contactsingle-info">
                            <h2>Website:</h2>
                            <p>http://www.yourwebsite.com</p>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <!-- Footer Copyright Area Start-->
    <div class="footer-copyright-area">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="footer-copyright">
                        <p>Copyright &copy; 2017, Marcos Ramayana. Todos os direitos reservados.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer Copyright Area End-->
</footer>
<!-- Footer End-->

<!-- Scroll to Top Start -->
<a href="#" class="scrollup">
    <i class="fa fa-angle-up"></i>
</a>
<!-- Scroll to Top End -->

<!-- Scripts Js Start -->
<script src="<?php echo $assets_base?>js/jquery-2.2.4.min.js"></script>
<script src="<?php echo $assets_base?>js/bootstrap.min.js"></script>
<script src="<?php echo $assets_base?>js/owl.carousel.min.js"></script>
<script src="<?php echo $assets_base?>js/owl.animate.js"></script>
<script src="<?php echo $assets_base?>js/jquery.magnific-popup.min.js"></script>
<script src="<?php echo $assets_base?>js/waypoints.min.js"></script>
<script src="<?php echo $assets_base?>js/jquery.counterup.min.js"></script>
<script src="<?php echo $assets_base?>js/modernizr.min.js"></script>
<script src="<?php echo $assets_base?>js/jquery.meanmenu.js"></script>
<script src="<?php echo $assets_base?>js/custom.js"></script>
<!-- Scripts Js End -->
</body>
</html>
