<!-- Footer Start-->
<footer>
    <div class="footer ">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-sm-6">
                    <div class="footer-wedget1">
                        <h2>Sobre</h2>
                        <p>O nosso objetivo é facilitar ao máximo o aprendizado do Direito Eleitoral, por meio de aulas
                            em vídeo e com a gradual leitura da legislação eleitoral e explicações das alterações
                            jurisprudenciais e doutrinárias.</p>


                        <a href="https://pt-br.facebook.com/marcosramayana/" target="_blank">
                            <img src="<?php echo $assets_base ?>/img/fb-logo-footer.png"/>
                        </a>


                        <a href="https://www.youtube.com/channel/UCpH9lpd3VRrzZEo18sd1xFQ" target="_blank"
                           style="margin-left: 15px;">
                            <img src="<?php echo $assets_base ?>/img/yt-logo-footer.png"/>
                        </a>

                        <a href="https://instagram.com/professorramayana" target="_blank" style="margin-left: 15px;">
                            <img src="<?php echo $assets_base ?>/img/instagram-logo-footer.png"/>
                        </a>

                    </div>
                </div>
                <div class="col-md-3 col-sm-6">
                    <div class="footer-wedget2">
                        <h2>Menu</h2>
                        <ul>
                            <li><a href="<?php echo $base_url ?>">Home</a></li>
                            <li><a href="<?php echo $base_url ?>/videos">Videos</a></li>
                            <li><a href="<?php echo $base_url ?>/aulas">Aulas</a></li>
                            <li><a href="<?php echo $base_url ?>/textos">Textos</a></li>
                            <li><a href="<?php echo $base_url ?>/informes">Informes</a></li>
                            <li><a href="<?php echo $base_url ?>/professor">Professor</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6">
                    <div class="contact-info">
                        <h2>Contato</h2>
                        <div class="contactsingle-info">
                            <h2>Email: </h2>
                            <p>professorramayana@gmail.com</p>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <!-- Footer Copyright Area Start-->
    <div class="footer-copyright-area">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="footer-copyright">
                        <p>Copyright &copy; 2017, Marcos Ramayana. Todos os direitos reservados.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer Copyright Area End-->
</footer>
<!-- Footer End-->

<!-- Scroll to Top Start -->
<a href="#" class="scrollup">
    <i class="fa fa-angle-up"></i>
</a>
<!-- Scroll to Top End -->

<!-- Scripts Js Start -->
<script src="<?php echo $assets_base ?>js/jquery-2.2.4.min.js"></script>
<script src="<?php echo $assets_base ?>js/bootstrap.min.js"></script>
<script src="<?php echo $assets_base ?>js/owl.carousel.min.js"></script>
<script src="<?php echo $assets_base ?>js/owl.animate.js"></script>
<script src="<?php echo $assets_base ?>js/jquery.magnific-popup.min.js"></script>
<script src="<?php echo $assets_base ?>js/waypoints.min.js"></script>
<script src="<?php echo $assets_base ?>js/jquery.counterup.min.js"></script>
<script src="<?php echo $assets_base ?>js/modernizr.min.js"></script>
<script src="<?php echo $assets_base ?>js/jquery.meanmenu.js"></script>
<script src="<?php echo $assets_base ?>js/custom.js"></script>
<!-- Scripts Js End -->
</body>
</html>
