<!DOCTYPE html>
<html dir="ltr" lang="en">
<head>

    <!-- Meta Tags -->
    <meta name="viewport" content="width=device-width,initial-scale=1.0"/>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
    <meta name="description" content="EduLight - University and Education HTML5 Template">
    <meta name="keywords" content="business, course, education, event, shopping, classes, e-learning, instructor, lessons, Online Learning, school, studying, teaching, tutoring, university">
    <meta name="author" content="a3z_themes">
    <!-- Title -->
    <title>Professor Ramayana</title>
    <!-- Favicon -->
    <link rel="icon" type="image/png" href="<?php echo $assets_base?>img/favicon.png">
    <!-- Apple Touch Icons -->
    <link rel="apple-touch-icon" href="<?php echo $assets_base?>img/apple-touch-icon.png">
    <link rel="apple-touch-icon" sizes="57x57" href="<?php echo $assets_base?>img/apple-touch-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="72x72" href="<?php echo $assets_base?>img/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="<?php echo $assets_base?>img/apple-touch-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="<?php echo $assets_base?>img/apple-touch-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="<?php echo $assets_base?>img/apple-touch-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="<?php echo $assets_base?>img/apple-touch-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="<?php echo $assets_base?>img/apple-touch-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="<?php echo $assets_base?>img/apple-touch-icon-180x180.png">

    <!-- Stylesheets -->
    <link rel="stylesheet" href="<?php echo $assets_base?>css/bootstrap.min.css">
    <link rel="stylesheet" href="<?php echo $assets_base?>css/owl.carousel.min.css">
    <link rel="stylesheet" href="<?php echo $assets_base?>css/owl.carousel.min.css">
    <link rel="stylesheet" href="<?php echo $assets_base?>css/animate.css">
    <link rel="stylesheet" href="<?php echo $assets_base?>css/magnific-popup.css">
    <link rel="stylesheet" href="<?php echo $assets_base?>css/meanmenu.min.css">
    <link rel="stylesheet" href="<?php echo $assets_base?>css/main.css">
    <link rel="stylesheet" href="<?php echo $assets_base?>css/responsive.css">
    <link rel="stylesheet" href="<?php echo $assets_base?>css/style.css">
</head>
<body>
<div id="preloader">
    <div id="status"></div>
</div>
<!-- Header Start -->
<header>
    <div id="sticky" class="header">
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-12">
                    <div class="logo">
                        <a href="index.html"><img src="<?php echo $assets_base?>img/logo.png" alt=""></a>
                    </div>
                </div>
                <div class="col-md-9 col-sm-12">
                    <div class="nav-menu">
                        <!-- Nav Start -->
                        <nav>
                            <ul>
                                <li><a href="<?php echo $base_url?>">Home</a></li>
                                <li><a href="<?php echo $base_url?>/videos">Videos</a></li>
                                <li><a href="<?php echo $base_url?>/aulas">Aulas resumidas</a></li>
                                <li><a href="<?php echo $base_url?>/textos">Textos e Artigos</a></li>
                                <li><a href="<?php echo $base_url?>/informes">Informes</a></li>
                                <li><a href="<?php echo $base_url?>/sitios">Sitios</a></li>
                                <li><a href="<?php echo $base_url?>/professor">Professor</a></li>
                                <li><a href="<?php echo $base_url?>/contato">Contato</a></li>
                            </ul>
                        </nav>
                        <!-- Nav End -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Header End -->