<!-- Slider Start -->
<div class="main-slider">
    <div class="slide-carousel owl-item">
        <div class="item" style="background-image:url(<?php echo $assets_base ?>img/slider1.jpg);">
            <div class="overlay"></div>
            <div class="text">
                <div class="this-item">
                    <h2>Bem vindo!</h2>
                </div>
                <div class="this-item">
                    <h3>Estudos de Direito Eleitoral</h3>
                </div>
            </div>
        </div>
        <div class="item" style="background-image:url(<?php echo $assets_base ?>img/slider2.jpg);">
            <div class="overlay"></div>
            <div class="text">
                <div class="this-item">
                    <h2><?php echo $video_count ?> video aulas</h2>
                </div>
                <div class="this-item">
                    <h3></h3>
                </div>
                <div class="this-item">
                    <p><a href="<?php echo $base_url?>/videos">Assista agora</a></p>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Slider End -->
<!-- Course Start -->
<div class="course padding-tp-90-bt-70">
    <div class="container">
        <div class="row">
            <div class="title">
                <h1>Conteúdos dos vídeos</h1>
                <div class="border-shape"></div>
                <p>Nossas aulas são divididas nos seguintes temas</p>
            </div>
            <div class="box">
                <div class="col-md-4 col-sm-6 inner">
                    <div class="single-course">
                        <h3><a href="<?php echo $base_url?>/videos">Direitos Políticos</a></h3>
                        <div class="course-icon">
                            <p>Direitos Políticos, Pacto Internacional sobre Direitos Civis e Políticos,
                                etc.</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-sm-6 inner">
                    <div class="single-course">
                        <h3><a href="<?php echo $base_url?>/videos">Conceito de Direito Eleitoral</a></h3>
                        <div class="course-icon">
                            <p>Conceito de Direito Eleitoral, Democracia, etc.</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-sm-6 inner">
                    <div class="single-course">
                        <h3><a href="<?php echo $base_url?>/videos">Justiça Eleitoral</a></h3>
                        <div class="course-icon">
                            <p>Sistema Eleitoral Distrital, Espécies, etc.</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-sm-6 inner">
                    <div class="single-course">
                        <h3><a href="<?php echo $base_url?>/videos">Sistemas Eleitorais</a></h3>
                        <div class="course-icon">
                            <p>Função institucional, Normas funcionais de atuação, etc.</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-sm-6 inner">
                    <div class="single-course">
                        <h3><a href="<?php echo $base_url?>/videos">Ministério Público</a></h3>
                        <div class="course-icon">
                            <p>Base legal das regras sobre o alistamento eleitoral, Requerimento de
                                alistamento eleitoral – RAE, etc.</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-sm-6 inner">
                    <div class="single-course">
                        <div class="course-icon">
                            <h3><a href="<?php echo $base_url?>/videos">Partidos Políticos</a></h3>
                            <p>Conceito e Natureza Jurídica, Origem dos Partidos Políticos, etc.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Course End -->
<!-- Call To Actions Start -->
<div class="call-to-action-area">
    <div class="images-overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="call-to-action">
                    <div class="call-to-action-text">
                        <h2>Tenha acesso a <?php echo $video_count ?> vídeos agora!!!</h2>
                    </div>
                    <div class="call-to-action-button">
                        <ul>
                            <li><a href="<?php echo $base_url?>/videos">Assista agora</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
<!-- Call To Actions End -->
<!-- Latest News Area Start -->
<div class="latestnews-area padding-tp-90-bt-70">
    <div class="container">
        <div class="row">
            <div class="title">
                <h1>Últimas Aulas</h1>
                <div class="border-shape"></div>
            </div>


            <?php foreach ($aulas_list as $aula): ?>
                <div class="col-md-4 col-sm-4 ">
                    <div class="single-news margin-bottom-30">
                        <!-- <div class="single-news-thumb">
                            <img src="img/b1.jpg" alt=""/>
                        </div> -->
                        <div class="post-content">
                            <h2><a href="<?php echo BASE_URL . '/aulas/' . $aula->id ?>"><?php echo $aula->title ?></a></h2>
                            <p><?php echo $aula->description ?></p>
                            <a href="<?php echo BASE_URL . '/aulas/' . $aula->id ?>" class="readmore-button">
                                Leia mais
                            </a>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>


        </div>
    </div>
</div>
<!-- Latest News Area End -->
<!-- Event Start -->
<div class="event-area padding-tp-90-bt-70">
    <div class="container">
        <div class="row">
            <div class="title">
                <h1>Últimos textos e artigos</h1>
                <div class="border-shape"></div>
            </div>

            <?php foreach ($textos_list as $texto): ?>
                <div class="col-md-4 col-sm-4 ">
                    <div class="single-events  margin-bottom-30">
                        <div class="single-event-thumb">
                            <img src="<?php echo $texto->image ?>" alt=""/>
                        </div>
                        <div class="event-content">
                            <h3>
                                <a href="<?php echo BASE_URL . '/textos/' . $texto->id ?>"><?php echo $texto->title ?></a>
                            </h3>
                            <p><?php echo $texto->description ?></p>
                            <a href="<?php echo BASE_URL . '/textos/' . $texto->id ?>" class="readmore-button">Leia
                                mais</a>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>
<!-- Event End -->

<!-- Count-up Start -->
<div class="count-up-area">
    <div class="images-overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="count-up-item">
                    <h2 class="counter"><?php echo $video_count ?></h2>
                    <p>Videos</p>

                </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="count-up-item">
                    <h2 class="counter"><?php echo $aula_count ?></h2>
                    <p>Aulas</p>

                </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="count-up-item">
                    <h2 class="counter"><?php echo $texto_count ?></h2>
                    <p>Textos</p>

                </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="count-up-item">
                    <h2 class="counter"><?php echo $informe_count ?></h2>
                    <p>Informes</p>

                </div>
            </div>

        </div>
    </div>
</div>
<!-- Count-up End -->
