<!-- Page Title Start -->
<div class="page-title-area single-blog-page">
    <div class="image-overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-sm-6 col-xs-12">
                <span class="page-title"><?php echo $informe->title ?></span>
            </div>
        </div>
    </div>
</div>
<!-- Page Title End -->

<!-- Blog Start -->
<section class="blog">
    <div class="container">
        <div class="row">
            <div class="col-md-12">

                <!-- Blog Classic Start -->
                <div class="blog-grid">
                    <div class="row">
                        <div class="col-md-12">


                            <!-- Post Item Start -->
                            <div class="post-item">
                                <div class="text">
                                    <?php echo nl2br($informe->text) ?>
                                </div>
                            </div>
                            <!-- Post Item End -->

                        </div>

                    </div>
                </div>
                <!-- Blog Classic End -->


                <!-- Author Box Start -->
                <div class="author-box">
                    <div class="inner">
                        <div class="author-thumb">
                            <img src="<?php echo $assets_base ?>img/marcos-ramayana.jpg" alt="">
                        </div>
                        <div class="author-info">
                            <h3>Dr. Marcos Ramayana</h3>
                        </div>
                    </div>
                </div>
                <!-- Author Box End -->
            </div>
        </div>
    </div>
</section>
<!-- Blog End -->
