<!-- Page Title Start -->
<div class="page-title-area shop-page">
    <div class="image-overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-sm-6 col-xs-12">
                <span class="page-title">Textos</span>
            </div>
        </div>
    </div>
</div>
<!-- Page Title End -->

<!-- Cart Page Start -->
<div class="cart-page-area padding-tp-70-bt-50">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
              <ul class="blog-listitem">
                  <?php foreach ($textos as $texto): ?>
                      <li class="blog-listitens">
                          <a href="<?php echo $base_url . '/textos/' . $texto->id?>">
                            <h3 class="product-name">
                              <?php echo $texto->title ?>
                            </h3>
                            <p class="product-name">
                                <?php echo $texto->description ?>
                            </p>
                          </a>
                      </li>
                  <?php endforeach; ?>
              </ul>

            </div>

        </div>
    </div>
</div>
<!-- Cart Page End -->
