<!-- Page Title Start -->
<div class="page-title-area single-blog-page">
    <div class="image-overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-sm-6 col-xs-12">
                <span class="page-title">
                    Vídeos
                </span>
            </div>
        </div>
    </div>
</div>
<!-- Page Title End -->

<!-- Blog Start -->
<section class="blog">
    <div class="container">
        <div class="row">
            <div class="col-md-12">

                <!-- Blog Classic Start -->
                <div class="blog-grid">
                    <div class="row">
                        <div class="col-md-12">


                            <!-- Post Item Start -->
                            <div class="post-item">
                                <div class="text">
                                    <div class="fb-login-button" data-max-rows="1" data-size="large"
                                         data-button-type="login_with" data-show-faces="false"
                                         data-auto-logout-link="true" data-use-continue-as="true"
                                         onlogin="checkLoginState();"></div>
                                </div>
                            </div>
                            <!-- Post Item End -->

                        </div>

                    </div>
                </div>
                <!-- Blog Classic End -->
            </div>
        </div>
    </div>
</section>
<!-- Blog End -->

<script type="text/javascript">
    function checkLoginState() {
        FB.getLoginStatus(function (response) {
            if (response.status === 'connected') {
                var accessToken = response.authResponse.accessToken;
                console.log(response.authResponse);
                console.log(accessToken);

                //Redirect
                window.location = "<?php echo BASE_URL?>/videos/" + accessToken;
            }
        });
    }

    document.onreadystatechange = function () {
        if (document.readyState === "complete") {
            checkLoginState();
        }
    }
</script>
