<!-- Page Title Start -->
<div class="page-title-area single-blog-page">
    <div class="image-overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-sm-6 col-xs-12">
                <span class="page-title">
                    Vídeos
                </span>
            </div>
        </div>
    </div>
</div>
<!-- Page Title End -->

<!-- Blog Start -->
<section class="blog">

    <div class="video-content" style="margin: 2em 10%">
        <a name="pague_video">
            <iframe width="100%" height="500" src="https://www.youtube.com/embed/DET2y5UH1oU" frameborder="0"
                    allowfullscreen></iframe>
        </a>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-md-12">

                <!-- Blog Classic Start -->
                <div class="blog-grid">
                    <div class="row">
                        <div class="col-md-12">
                            <!-- Post Item Start -->
                            <div class="post-item" style="text-align: center !important;">
                                <p>Selecionamos diversos temas relevantes do <strong>Direito Eleitoral.</strong></p>

                                <p>As aulas em vídeo são de tempo reduzido, em média, 10 (dez) minutos.</p>

                                <p>O tempo de acesso ao conteúdo completo das aulas em vídeo é de <strong>3 (três)
                                        meses</strong>, após é necessária nova aquisição.</p>

                                <p>O investimento pelo período de tempo de: <strong>3 (três) meses</strong>.</p>

                                <p>O valor é de: <strong>R$ 30.00</strong></p>

                                <div class="fb-login-button" data-max-rows="1" data-size="large"
                                     data-button-type="login_with" data-show-faces="false"
                                     data-auto-logout-link="true" data-use-continue-as="true"
                                     onlogin="checkLoginState();"></div>
                            </div>
                            <!-- Post Item End -->

                        </div>
                    </div>
                </div>
                <!-- Blog Classic End -->


                <!-- gallery  Start -->
                <div class="gallery-area-area  padding-tp-70-bt-50">
                    <div class="container">
                        <div class="row">
                            <?php foreach ($videos as $video): ?>
                                <div class="col-md-6 col-sm-6">
                                    <h3><?php echo $video->title ?></h3>
                                    <div class="course-gallery margin-bottom-30 gallery-item">
                                        <img width="555" height="312"
                                             src="<?php echo $base_url ?>/uploads/<?php echo $video->thumb ?>"
                                             alt=""/>
                                        <div class="gallery-img-overlay"></div>
                                        <div class="gallery-overlay">
                                            <div class="gallery-item-text">
                                                <a href="#pague_video">
                                                    <img src="<?php echo $assets_base ?>img/lock.svg"
                                                         style="width: 60%">
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            <?php endforeach; ?>
                        </div>
                    </div>
                </div>
                <!-- gallery End -->
            </div>
        </div>
    </div>
</section>
<!-- Blog End -->
<script>
    function checkLoginState() {
        FB.getLoginStatus(function (response) {
            if (response.status === 'connected') {
                var accessToken = response.authResponse.accessToken;
                console.log(response.authResponse);
                console.log(accessToken);

                //Redirect
                window.location = "<?php echo BASE_URL?>/videos/" + accessToken;
            }
        });
    }

    document.onreadystatechange = function () {
        if (document.readyState === "complete") {
            checkLoginState();
        }
    }

    function openLightBox(code) {
        PagSeguroLightbox({
            code: code
        }, {
            success: function (transactionCode) {
                alert('Aguarde enquanto seu pagamento é processado.');
                location.reload(true);
//                window.location = "<?php //echo $base_url?>///pagseguro/payment_status/"+transactionCode;
            },
            abort: function () {

            }
        })
    }
</script>