<div class="page-title-area single-blog-page">
    <div class="image-overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-sm-6 col-xs-12">
                <span class="page-title">
                    Vídeos
                </span>
            </div>

            <div class="col-md-6 col-sm-6 col-xs-12" style="text-align: right !important;">
                <div class="fb-login-button" data-max-rows="1" data-size="large"
                     data-button-type="login_with" data-show-faces="false"
                     data-auto-logout-link="true" data-use-continue-as="true"
                     onlogin="checkLoginState();"></div>
            </div>
        </div>
    </div>
</div>

<!-- gallery  Start -->
<div class="gallery-area-area  padding-tp-70-bt-50">

    <div class="container">
        <div class="row">
            <?php foreach ($videos as $video): ?>

                <div class="col-md-6 col-sm-6">
                    <div class="course-gallery margin-bottom-30 gallery-item">
                        <h3><?php echo $video->title ?></h3>
                        <iframe src="https://www.youtube.com/embed/<?php echo getVideoIdFromYoutubeLink($video->video_link) ?>?controls=2&modestbranding=0&showinfo=0&origin=http://professorramayana.com&rel=0"
                                width="555" height="312" frameborder="0"
                                allowfullscreen></iframe>
                    </div>
                </div>

            <?php endforeach; ?>
        </div>
    </div>
</div>
<!-- gallery End -->


<script>
    function checkLoginState() {
        FB.getLoginStatus(function (response) {
            if (response.status !== 'connected') {
                window.location = "<?php echo BASE_URL?>/logout";
            }
        });
    }

    document.onreadystatechange = function () {
        if (document.readyState === "complete") {
            checkLoginState();
        }
    }

    function openLightBox(code) {
        PagSeguroLightbox({
            code: code
        }, {
            success: function (transactionCode) {
                alert('Aguarde enquanto seu pagamento é processado.');
                location.reload(true);
//                window.location = "<?php //echo $base_url?>///pagseguro/payment_status/"+transactionCode;
            },
            abort: function () {

            }
        })
    }
</script>