<h1>Editar Vídeo</h1>

<h3>
    <a href="<?php echo $base_url ?>/admin/videos/list">Voltar</a>
</h3>

<form action="<?php echo $base_url ?>/admin/videos/edit/<?php echo $row->id ?>" method="POST" id="postForm"
      enctype="multipart/form-data">
    <input type="hidden" name="fromForm" value="true">
    <div class="form-group">
        <label for="title">Título:</label>
        <input type="text" class="form-control" value="<?php echo $row->title ?>" name="title" id="titulo">
    </div>
    <div class="form-group">
        <label for="description">Descrição:</label>
        <input type="text" class="form-control" name="description" id="description"
               value="<?php echo $row->description ?>">
    </div>
    <div class="form-group">
        <label for="text">Texto:</label> <br/>
        <textarea class="form-control" rows="5" id="text" name="text"><?php echo $row->text ?></textarea>
    </div>

    <div class="form-group">
        <label for="text">Categoria:</label> <br/>
        <input type="text" class="form-control" name="category" id="category" value="<?php echo $row->category ?>">

    </div>


    <div class="form-group">
        <label for="video_link">Link do video:</label> <br/>
        <input type="text" class="form-control" name="video_link" id="video_link"
               value="<?php echo $row->video_link ?>">
    </div>

    <div class="form-group">
        <label>Vídeo atual:</label> <br/>
        <div style="position:relative;height:0;padding-bottom:56.25%">
            <div style="position:relative;height:0;padding-bottom:56.25%">
                <iframe src="https://www.youtube.com/embed/<?php echo $row->video_id?>?ecver=2" width="640" height="360" frameborder="0"
                        style="position:absolute;width:100%;height:100%;left:0" allowfullscreen></iframe>
            </div>
        </div>
    </div>

    <button type="submit" id="submit" class="btn btn-default">Salvar</button>
</form>
<script>
</script>
