<h1>Vídeos</h1>


<a href="<?php echo $base_url ?>/admin/videos/create">Novo vídeo</a>

<table class="table table-hover">
    <thead>
    <tr>
        <th>Título</th>
        <th>Texto</th>
        <th>Vídeo</th>
        <th></th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($rows as $row): ?>
        <tr>
            <td><?php echo $row->title ?></td>
            <td><?php echo $row->text ?></td>
            <td>
                <a target="_blank" href="<?php echo $row->video_link ?>">
                    <?php echo $row->video_link ?>
                </a>
            </td>
            <td>
                <a class="btn btn-link"
                   href="<?php echo $base_url ?>/admin/videos/edit/<?php echo $row->id ?>">Editar</a>
            </td>
            <td>
                <form action="<?php echo $base_url ?>/admin/videos/delete" method="POST"
                      id="postForm" enctype="multipart/form-data" onsubmit="return confirmDelete()">
                    <input type="hidden" name="id" value="<?php echo $row->id ?>"/>
                    <input type="submit" class="btn btn-link" value="Excluir"/>
                </form>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>