<h1>Configurações</h1>

<table class="table table-hover">
    <thead>
    <tr>
        <th>Configuração</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>Tempo de Acesso</td>
        <td>
            <a href="<?php echo $base_url ?>/admin/config/edit/tempo_acesso">Editar</a>
        </td>
    </tr>
    <tr>
        <td>Valor Pagamento</td>
        <td>
            <a href="<?php echo $base_url ?>/admin/config/edit/valor_acesso">Editar</a>
        </td>
    </tr>
    </tbody>
</table>
