<h1>Editar Período</h1>

<h3>
    <a href="<?php echo $base_url ?>/admin/config/list">Voltar</a>
</h3>

<form action="<?php echo $base_url ?>/admin/config/edit_tempo/<?php echo $row->id ?>" method="POST" id="postForm"
      enctype="multipart/form-data">
    <input type="hidden" name="fromForm" value="true">
    <div class="form-group">
        <label for="text">Meses:</label> <br/>
        <input type="text" class="form-control" name="meses" id="meses"
               value="<?php echo $row->value ?>">

    </div>
    <button type="submit" id="submit" class="btn btn-default">Salvar</button>
</form>
<script>
</script>
