-- MySQL Script generated by MySQL Workbench
-- Mon Aug 28 20:51:55 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ramayana
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ramayana
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ramayana` DEFAULT CHARACTER SET utf8 ;
USE `ramayana` ;

-- -----------------------------------------------------
-- Table `ramayana`.`textos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ramayana`.`textos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `description` VARCHAR(3000) NOT NULL,
  `text` TEXT NOT NULL,
  `image` VARCHAR(3000) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ramayana`.`aulas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ramayana`.`aulas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `description` VARCHAR(3000) NOT NULL,
  `text` TEXT NOT NULL,
  `image` VARCHAR(3000) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ramayana`.`sobre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ramayana`.`sobre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `description` VARCHAR(3000) NOT NULL,
  `text` TEXT NOT NULL,
  `image` VARCHAR(3000) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ramayana`.`sitios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ramayana`.`sitios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `description` VARCHAR(3000) NOT NULL,
  `text` TEXT NOT NULL,
  `image` VARCHAR(3000) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ramayana`.`informes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ramayana`.`informes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `description` VARCHAR(3000) NOT NULL,
  `text` TEXT NOT NULL,
  `image` VARCHAR(3000) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ramayana`.`videos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ramayana`.`videos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `description` VARCHAR(3000) NULL,
  `text` TEXT NULL,
  `link` VARCHAR(255) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `category` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ramayana`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ramayana`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `facebook_id` VARCHAR(255) NOT NULL,
  `facebook_access_token` VARCHAR(255) NULL,
  `payment_transaction_id` VARCHAR(255) NULL,
  `access_expiration_date` DATE NULL,
  `welcome_email_sent` TINYINT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `ramayana`.`transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ramayana`.`transactions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ref` VARCHAR(255) NOT NULL,
  `product` VARCHAR(255) NOT NULL,
  `value` DOUBLE(10,2) NOT NULL,
  `is_paid` TINYINT NULL,
  `payment_date` DATETIME NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuarios_id`),
  INDEX `fk_transactions_usuarios_idx` (`usuarios_id` ASC),
  UNIQUE INDEX `ref_UNIQUE` (`ref` ASC),
  CONSTRAINT `fk_transactions_usuarios`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `ramayana`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `ramayana`.`informes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ramayana`.`config` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `key` VARCHAR(255) NOT NULL,
  `value` VARCHAR(3000) NOT NULL,
  `description` VARCHAR(3000) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
