<h1>Editar <?php echo $row->title?></h1>

<h3>
    <a href="<?php echo $base_url ?>/admin/sobre/list">Voltar</a>
</h3>

<form action="<?php echo $base_url ?>/admin/sobre/edit/<?php echo $row->id ?>" method="POST" id="postForm"
      enctype="multipart/form-data">
    <input type="hidden" name="fromForm" value="true">
    <div class="form-group">
        <label for="title">Título: <?php echo $row->title?></label>

    </div>
    <div class="form-group">
        <label for="description">Descrição: <?php echo $row->description ?></label>
    </div>
    <div class="form-group">
        <label for="text">Texto:</label> <br/>
        <textarea class="form-control" rows="5" id="text" name="text"><?php echo $row->text ?></textarea>
    </div>

    <button type="submit" id="submit" class="btn btn-default">Salvar</button>
</form>
<script>
</script>
