<h1>Sobre</h1>
<table class="table table-hover">
    <thead>
    <tr>
        <th>Campo</th>
        <th></th>

    </tr>
    </thead>
    <tbody>
    <tr>
        <td>Professor</td>
        <td>
            <a href="<?php echo $base_url ?>/admin/sobre/edit/professor">Editar</a>
        </td>
    </tr>
    <tr>
        <td>Vídeos</td>
        <td>
            <a href="<?php echo $base_url ?>/admin/sobre/edit/videos">Editar</a>
        </td>
    </tr>
    </tbody>
</table>