<h1>Editar Vídeo</h1>

<h3>
    <a href="<?php echo $base_url ?>/forms/videos/list">Voltar</a>
</h3>

<form action="<?php echo $base_url ?>/videos/edit/<?php echo $row->id ?>" method="POST" id="postForm"
      enctype="multipart/form-data">
    <input type="hidden" name="fromForm" value="true">
    <div class="form-group">
        <label for="title">Título:</label>
        <input type="text" class="form-control" value="<?php echo $row->title ?>" name="title" id="titulo">
    </div>
    <div class="form-group">
        <label for="description">Descrição:</label>
        <input type="text" class="form-control" name="description" id="description"
               value="<?php echo $row->description ?>">
    </div>
    <div class="form-group">
        <label for="text">Texto:</label> <br/>
        <textarea class="form-control" rows="5" id="text" name="text"><?php echo $row->text ?></textarea>
    </div>

    <div class="form-group">
        <label for="text">Categoria:</label> <br/>
        <input type="text" class="form-control" name="category" id="category" value="<?php echo $row->category ?>">

    </div>


    <div class="form-group">
        <label for="text">Link do video:</label> <br/>
        <input type="text" class="form-control" name="video_link" id="video_link" value="<?php echo $row->video_link ?>">
    </div>


    <button type="submit" id="submit" class="btn btn-default">Salvar</button>
</form>
<script>
</script>
