<h1>Vídeos</h1>


<a href="<?php echo $base_url ?>/forms/videos/create">Novo vídeo</a>

<table class="table table-hover">
    <thead>
    <tr>
        <th>Título</th>
        <th>Texto</th>
        <th>Vídeo</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($rows as $row): ?>
        <tr>
            <td><?php echo $row->title ?></td>
            <td><?php echo $row->text ?></td>
            <td>
                <a target="_blank" href="<?php echo $row->video_link ?>">
                    <?php echo $row->video_link ?>
                </a>
            </td>
            <td>
                <a href="<?php echo $base_url ?>/forms/videos/edit/<?php echo $row->id ?>">Editar</a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>