<h1>Editar Informe</h1>

<h3>
    <a href="<?php echo $base_url ?>/forms/informes/list">Voltar</a>
</h3>

<form action="<?php echo $base_url ?>/informes/edit/<?php echo $row->id ?>" method="POST" id="postForm"
      enctype="multipart/form-data">
    <input type="hidden" name="fromForm" value="true">
    <div class="form-group">
        <label for="title">Título:</label>
        <input type="text" class="form-control" value="<?php echo $row->title ?>" name="title" id="titulo">
    </div>
    <div class="form-group">
        <label for="description">Descrição:</label>
        <input type="text" class="form-control" name="description" id="description"
               value="<?php echo $row->description ?>">
    </div>
    <div class="form-group">
        <label for="text">Texto:</label> <br/>
        <textarea class="form-control" rows="5" id="text" name="text"><?php echo $row->text ?></textarea>
    </div>

    <div class="form-group">
        <label for="image">Selecione uma imagem:</label> <br/>
        <input type="file" accept="image/png, image/jpeg, image/gif" name="image" id="image"/> <!-- rename it -->
    </div>

    <div class="form-group">
        <label for="image">Imagem atual:</label> <br/>
        <img src="<?php echo $row->image ?>" class="img-thumbnail" width="304" height="236">
    </div>

    <button type="submit" id="submit" class="btn btn-default">Salvar</button>
</form>
<script>
</script>
