<h1>Textos</h1>


<a href="<?php echo $base_url?>/forms/textos/create">Novo texto</a>

<table class="table table-hover">
    <thead>
    <tr>
        <th>Título</th>
        <th>Texto</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($rows as $row): ?>
        <tr>
            <td><?php echo $row->title ?></td>
            <td><?php echo $row->text ?></td>
            <td>
                <a href="<?php echo $base_url?>/forms/textos/edit/<?php echo $row->id?>">Editar</a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>